[package]
name = "rpr"
version = "0.1.0"
authors = ["robmikh <rob.mikh@outlook.com>"]
description = "A utility to record ETW traces."
edition = "2021"

[dependencies]
bytemuck = "1.8.0"
clap = { version = "3.1.5", features = ["derive"] }

[dependencies.windows]
version = "0.33.0"
features = [
    "alloc",
    "Win32_Foundation",
    "Win32_System_Diagnostics_Etw",
    "Win32_System_Time",
]
